### ISSUE TITLE
Saved Records: Error when sorting (possibly due to old save records)

### ISSUE THREAD

**Issue by kristenGRI** [gri-is/portal#513]
I had an issue where certain set options would not work and create an error in my console. After I cleared my cache, saved new records, I could not reproduce the issue. Noting this was happening on my local (where I obviously had a lot of saved records that accumulated over some time) and http://grpdev.getty.edu:8080/ where I also had records saved.

I am not sure if this is due to data being overwritten when added to the portal and the saved records remain, but these are the errors I was receiving:

angular.js:12722Error: [ngRepeat:dupes] http://errors.angularjs.org/1.4.9/ngRepeat/dupes?p0=book%20in%20savedRecord…%22%3A%22bnf_bpt6k63443180%22%2C%22%24%24hashKey%22%3A%22object%3A88%22%7D
    at Error (native)
    at http://local.portal.dev:8000/bower_components/angular/angular.min.js:6:416
    at http://local.portal.dev:8000/bower_components/angular/angular.min.js:283:377
    at Object.fn (http://local.portal.dev:8000/bower_components/angular/angular.min.js:130:209)
    at r.$digest (http://local.portal.dev:8000/bower_components/angular/angular.min.js:131:291)
    at r.$apply (http://local.portal.dev:8000/bower_components/angular/angular.min.js:134:236)
    at HTMLAnchorElement.<anonymous> (http://local.portal.dev:8000/bower_components/angular/angular.min.js:257:229)
    at Of (http://local.portal.dev:8000/bower_components/angular/angular.min.js:35:394)
    at HTMLAnchorElement.Nf.d (http://local.portal.dev:8000/bower_components/angular/angular.min.js:35:341)(anonymous function) @ angular.js:12722
angular.js:12722Error: [ngRepeat:dupes] http://errors.angularjs.org/1.4.9/ngRepeat/dupes?p0=book%20in%20savedRecord…%22%3A%22malaga_10630_4136%22%2C%22%24%24hashKey%22%3A%22object%3A87%22%7D
    at Error (native)
    at http://local.portal.dev:8000/bower_components/angular/angular.min.js:6:416
    at http://local.portal.dev:8000/bower_components/angular/angular.min.js:283:377
    at Object.fn (http://local.portal.dev:8000/bower_components/angular/angular.min.js:130:209)
    at r.$digest (http://local.portal.dev:8000/bower_components/angular/angular.min.js:131:291)
    at r.$apply (http://local.portal.dev:8000/bower_components/angular/angular.min.js:134:236)
    at HTMLAnchorElement.<anonymous> (http://local.portal.dev:8000/bower_components/angular/angular.min.js:257:229)
    at Of (http://local.portal.dev:8000/bower_components/angular/angular.min.js:35:394)
    at HTMLAnchorElement.Nf.d (http://local.portal.dev:8000/bower_components/angular/angular.min.js:35:341)(anonymous function) @ angular.js:12722

**Comment by susanley** [comment]
@kristenGRI and I discussed. Since the error complains of duplicate keys and values, we think it's worth leaving this open and checking on it again when @alyxrossetti adds new data and/or restructures data.
