### ISSUE TITLE
critical bug in API

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#644]
A user reported that when searching for "tapisseries" he got an error. See http://portal.getty.edu/search?q=tapiserries&from=0&size=25&sort=relevance

Here is the Django error message:

``` bash
Internal Server Error: /api/books/q=tapestries
Traceback (most recent call last):
  File "/apps/portal/ENV/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/apps/portal/ENV/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/apps/portal/ENV/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/apps/portal/ENV/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/apps/portal/ENV/lib/python3.4/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/apps/portal/src/server/api/views.py", line 95, in get
    query = es_functions.create_multisearch(body, search_options.get('from'), search_options.get('size'), filters)
  File "/apps/portal/src/server/api/es_functions.py", line 200, in create_multisearch
    {'size': size[0],
TypeError: 'NoneType' object is not subscriptable

Request repr():
<WSGIRequest
path:/api/books/q=tapestries,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'FIS-PORTAL-PSJSESSIONID': 'h42ROV-Ex-9W64chJVGmn9o3cWKCBPcs!-1078698087',
 'https%3a%2f%2ffis.getty.edu%2fpsp%2ffis%2femployee%2ferp%2frefresh': 'list:%20%3Ftab%3Dremoteunifieddashboard%7C%3Frp%3Dremoteunifieddashboard'},
META:{'CONTEXT_DOCUMENT_ROOT': '/apps/portal/src/client',
 'CONTEXT_PREFIX': '',
 'CSRF_COOKIE': 'WbS3gfMCCaCL6TwqH3UvtnR3uqMDZ9R0',
 'DOCUMENT_ROOT': '/apps/portal/src/client',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'FIS-PORTAL-PSJSESSIONID=h42ROV-Ex-9W64chJVGmn9o3cWKCBPcs!-1078698087; '
                'https%3a%2f%2ffis.getty.edu%2fpsp%2ffis%2femployee%2ferp%2frefresh=list:%20%3Ftab%3Dremoteunifieddashboard%7C%3Frp%3Dremoteunifieddashboard',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'portal.getty.edu',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) '
                    'Gecko/20100101 Firefox/49.0',
 'PATH_INFO': '/books/q=tapestries',
 'PATH_TRANSLATED': '/apps/portal/src/client/index.html',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '153.10.131.158',
 'REMOTE_PORT': '54288',
 'REQUEST_METHOD': 'GET',
 'REQUEST_SCHEME': 'http',
 'REQUEST_URI': '/api/books/q=tapestries',
 'SCRIPT_FILENAME': '/apps/portal/src/server/server/wsgi.py',
 'SCRIPT_NAME': '/api',
 'SCRIPT_URI': 'http://portal.getty.edu/api/books/q=tapestries',
 'SCRIPT_URL': '/api/books/q=tapestries',
 'SERVER_ADDR': '153.10.243.52',
 'SERVER_ADMIN': 'griis@getty.edu',
 'SERVER_NAME': 'portal.getty.edu',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.4.6 (Red Hat Enterprise Linux) mod_wsgi/4.5.2 '
                    'Python/3.4.3',
 'apache.version': (2, 4, 6),
 'mod_wsgi.application_group': 'portal.getty.edu|/api',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.listener_host': '153.10.243.52',
 'mod_wsgi.listener_port': '80',
 'mod_wsgi.path_info': '/books/q=tapestries',
 'mod_wsgi.process_group': '',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.request_start': '1476203530227551',
 'mod_wsgi.script_name': '/api',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.script_start': '1476203530227958',
 'mod_wsgi.thread_id': 0,
 'mod_wsgi.thread_requests': 2,
 'mod_wsgi.total_requests': 2,
 'mod_wsgi.version': (4, 5, 2),
 'wsgi.errors': <_io.TextIOWrapper encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'mod_wsgi.FileWrapper'>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f6ae2c8d030>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
Getting too much email from root@localhost? You can unsubscribe 
```

**Comment by jfranco-gri** [comment]
What did you do to get that error message? While I am experiencing an issue with that search term, the error I am getting is different than that. I'm wondering if there is more than one problem here.

**Comment by joshuago78** [comment]
I typed an api query directly into the browser.
```bash
'REQUEST_URI': '/api/books/q=tapestries',
```
note that 'tapisseries' is French for tapestries.

The Django error does not display to the user. The error messages are sent directly to me because I am listed as an admin in the Django settings.

**Comment by joshuago78** [comment]
I noticed that I did not include the `?` in the URL. Even with the correct usage, the same error exists: 

```bash
Internal Server Error: /api/books/
Traceback (most recent call last):
  File "/apps/portal/ENV/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/apps/portal/ENV/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/apps/portal/ENV/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/apps/portal/ENV/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/apps/portal/ENV/lib/python3.4/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/apps/portal/src/server/api/views.py", line 95, in get
    query = es_functions.create_multisearch(body, search_options.get('from'), search_options.get('size'), filters)
  File "/apps/portal/src/server/api/es_functions.py", line 200, in create_multisearch
    {'size': size[0],
TypeError: 'NoneType' object is not subscriptable

Request repr():
<WSGIRequest
path:/api/books/,
GET:{'from': '0',
 'q': 'tapisseries',
 'size': '25',
 'sort': 'relevance'},
POST:<QueryDict: {}>,
COOKIES:{'FIS-PORTAL-PSJSESSIONID': 'h42ROV-Ex-9W64chJVGmn9o3cWKCBPcs!-1078698087',
 'https%3a%2f%2ffis.getty.edu%2fpsp%2ffis%2femployee%2ferp%2frefresh': 'list:%20%3Ftab%3Dremoteunifieddashboard%7C%3Frp%3Dremoteunifieddashboard'},
META:{'CONTEXT_DOCUMENT_ROOT': '/apps/portal/src/client',
 'CONTEXT_PREFIX': '',
 'CSRF_COOKIE': 'ImRSXaMcUC7NBw0luZPQT5DDU6Q1rS1K',
 'DOCUMENT_ROOT': '/apps/portal/src/client',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'FIS-PORTAL-PSJSESSIONID=h42ROV-Ex-9W64chJVGmn9o3cWKCBPcs!-1078698087; '
                'https%3a%2f%2ffis.getty.edu%2fpsp%2ffis%2femployee%2ferp%2frefresh=list:%20%3Ftab%3Dremoteunifieddashboard%7C%3Frp%3Dremoteunifieddashboard',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'portal.getty.edu',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) '
                    'Gecko/20100101 Firefox/49.0',
 'PATH_INFO': '/books/',
 'PATH_TRANSLATED': '/apps/portal/src/client/index.html',
 'QUERY_STRING': 'q=tapisseries&from=0&size=25&sort=relevance',
 'REMOTE_ADDR': '153.10.131.158',
 'REMOTE_PORT': '56272',
 'REQUEST_METHOD': 'GET',
 'REQUEST_SCHEME': 'http',
 'REQUEST_URI': '/api/books/?q=tapisseries&from=0&size=25&sort=relevance',
 'SCRIPT_FILENAME': '/apps/portal/src/server/server/wsgi.py',
 'SCRIPT_NAME': '/api',
 'SCRIPT_URI': 'http://portal.getty.edu/api/books/',
 'SCRIPT_URL': '/api/books/',
 'SERVER_ADDR': '153.10.243.52',
 'SERVER_ADMIN': 'griis@getty.edu',
 'SERVER_NAME': 'portal.getty.edu',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.4.6 (Red Hat Enterprise Linux) mod_wsgi/4.5.2 '
                    'Python/3.4.3',
 'apache.version': (2, 4, 6),
 'mod_wsgi.application_group': 'portal.getty.edu|/api',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.listener_host': '153.10.243.52',
 'mod_wsgi.listener_port': '80',
 'mod_wsgi.path_info': '/books/',
 'mod_wsgi.process_group': '',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.request_start': '1476212972693001',
 'mod_wsgi.script_name': '/api',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.script_start': '1476212972693361',
 'mod_wsgi.thread_id': 0,
 'mod_wsgi.thread_requests': 1,
 'mod_wsgi.total_requests': 1,
 'mod_wsgi.version': (4, 5, 2),
 'wsgi.errors': <_io.TextIOWrapper encoding='utf-8'>,
 'wsgi.file_wrapper': <class 'mod_wsgi.FileWrapper'>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f6ae2c5f168>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

**Comment by jfranco-gri** [comment]
The lack of a question mark is kind of a red herring. It looks like it when you include it, the url regex doesn't parse the url correctly and nothing gets set to the params value so it eventually errors out when trying to process the params (I don't include a question mark in any of the API calls).

The previous error you were getting was also a red herring. You were getting that specific error because you weren't adding a 'size' parameter, which the query building function expects, so it error when trying to process that. But most importantly, you used the term "tapestries" instead of "tapistries" which bypassed the real issue.  When you use the term "tapistries" or "tapiserries" we see the real issue, which is when the api call contains the term "api" (or "json" or "xml"). When we include those, we get this error:

```
Using the URLconf defined in server.urls, Django tried these URL patterns, in this order:
^admin/
^api/ ^book/(?!raw/)(?P<id>(?:(?!.json|.xml|.api).)*)$ [name='book']
^api/ ^book/(?!raw/)(?P<id>(?:(?!.json|.xml|.api).)*)\.(?P<format>[a-z0-9]+)/?$ [name='book']
^api/ ^book/raw/(?P<id>(?:(?!.json|.xml|.api|.ris).)*)$ [name='raw']
^api/ ^book/raw/(?P<id>(?:(?!.json|.xml|.api|.ris).)*)\.(?P<format>[a-z0-9]+)/?$ [name='raw']
^api/ ^books/(?P<params>(?:(?!.json|.api|.xml).)*?)[/]?$ [name='books']
^api/ ^books/(?P<params>(?:(?!.json|.api|.xml).)*?)[/]?\.(?P<format>[a-z0-9]+)/?$ [name='books']
^api/ ^contributors[/]?$ [name='contributors']
^api/ ^contributors[/]?\.(?P<format>[a-z0-9]+)/?$ [name='contributors']
^api/ ^send-email[/]?$ [name='send-email']
^api/ ^send-email[/]?\.(?P<format>[a-z0-9]+)/?$ [name='send-email']
The current URL, api/books/q=api&size=25&from=0, didn't match any of these.
```

As you can see, the urls don't match anything that contains ".api" or ".json" or ".xml". This is because when we have a query like `http://127.0.0.1:8000/api/books/q=art&from=0&size=25&sort=relevance.json` we only want to set the params value to `q=art&from=0&size=25&sort=relevance` instead of `q=art&from=0&size=25&sort=relevance.json`  However, this seems to cause a bug when we want the search term to contain 'api' or 'json' or 'xml' (as in the case of 'tapiseries') so we'll have to figure out a different way of handling that.
